### Add key-value pair
PUT http://localhost:9000/items/name
Content-Type: application/json

{
  "value": "Bob"
}

###
PUT http://localhost:9000/items/url
Content-Type: application/json

{
  "value": "http://www.example.com"
}

###
PUT http://localhost:9000/items/url
Content-Type: application/json

{
  "value": "http://www.example.com",
  "ttl": "1h"
}

###
PUT http://localhost:9000/items/object
Content-Type: application/json

{
  "value": {
    "a": "test",
    "b": "test2",
    "c": 3
  }
}

###
GET http://localhost:9000/items

###
GET http://localhost:9000/items/url

###
GET http://localhost:9000/stats

###
DELETE http://localhost:9000/items/object

###
POST http://localhost:9000/snapshot